version: "3.9"
services:
  api-gateway:
    build: .
    container_name: api-gateway
    restart: always
    volumes:
      - .:/usr/src/api-gateway
    networks:
      - micro-service
    ports:
      - ${PORT}:${PORT}

networks:
  micro-service:
    name: micro-service
